# MSFE-YOLO custom config (YOLOv8n + feature enhancement modules)

# Parameters
nc: 10  # number of classes (update based on VisDrone)
depth_multiple: 0.33
width_multiple: 0.50

# Backbone
backbone:
  [
    [-1, 1, Conv, [64, 3, 1]],
    [-1, 1, Conv, [128, 3, 2]],
    [-1, 3, SCF, [128]],          # Symmetric C2f
    [-1, 1, Conv, [256, 3, 2]],
    [-1, 3, SCF, [256]],
    [-1, 1, Conv, [512, 3, 2]],
    [-1, 1, EMA, [512]],          # Efficient Multiscale Attention
  ]

# Head
head:
  [
    [-1, 1, Conv, [256, 1, 1]],
    [-1, 1, FF, [256]],           # Feature Fusion
    [-1, 1, Detect, [nc]],        # Output layer
  ]
